[package]
name = "starkhack_qw"
version = "0.1.0"
license = "MIT"
authors = []
keywords = []
description = "An awesome Starknet project"

repository = "https://github.com/0xnilesh/starkhack_qw"

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
# TODO: Make Starknet version configurable
starknet = ">=2.1.0"
# TODO: Make alexandria dependency optional
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[tool.snforge]
exit_first = false
